# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
        GOROOT: ./server/
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: mod init
      run: |
          go mod init httpDLM
          go mod tidy
          go get github.com/gin-gonic/gin
      
    - name: Build
      run: go build -v  -o httpDLM ./server/cmd/main.go

